name = "GaussianSpec"
version = "0.1.0"

[[lean_lib]]
name = "GaussianSpec"

[[lean_exe]]
name = "gaussianspec"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[require]]
name = "LeanSearchClient"
git = "https://github.com/leanprover-community/LeanSearchClient"
rev = "main"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"
