/-!
{
  "name": "numpy.busdaycalendar",
  "category": "Business day operations",
  "description": "A business day calendar object that efficiently stores information defining valid days for the busday family of functions",
  "url": "https://numpy.org/doc/stable/reference/generated/numpy.busdaycalendar.html",
  "doc": "busdaycalendar(weekmask='1111100', holidays=None)\n\nA business day calendar object that efficiently stores information defining valid days for the busday family of functions.\n\nThe default valid days are Monday through Friday (\"business days\"). A busdaycalendar object can be specified with any set of weekly valid days, plus an optional \"holiday\" dates that always will be invalid.\n\nOnce a busdaycalendar object is created, the weekmask and holidays cannot be modified.\n\nParameters\n----------\nweekmask : str or array_like of bool, optional\n    A seven-element array indicating which of Monday through Sunday are valid days. May be specified as a length-seven list or array, like [1,1,1,1,1,0,0]; a length-seven string, like '1111100'; or a string like \"Mon Tue Wed Thu Fri\", made up of 3-character abbreviations for weekdays, optionally separated by white space. Valid abbreviations are: Mon Tue Wed Thu Fri Sat Sun\nholidays : array_like of datetime64[D], optional\n    An array of dates to consider as invalid dates, no matter which weekday they fall upon. Holiday dates may be specified in any order, and NaT (not-a-time) dates are ignored. This list is saved in a normalized form that is suited for fast calculations of valid days.\n\nReturns\n-------\nout : busdaycalendar\n    A business day calendar object containing the specified weekmask and holidays values.\n\nAttributes\n----------\nweekmask : (copy) seven-element array of bool\nholidays : (copy) sorted array of datetime64[D]",
  "code": "# C implementation for performance\n# A business day calendar object that efficiently stores information defining valid days for the busday family of functions\n#\n# This function is implemented in C as part of NumPy's core multiarray module.\n# The C implementation provides:\n# - Optimized memory access patterns\n# - Efficient array manipulation\n# - Low-level control over data layout\n# - Integration with NumPy's array object internals\n#\n# Source: C implementation in numpy/_core/src/multiarray/datetime_busday.c"
}
-/

-- TODO: Implement busdaycalendar
