/-!
{
  "name": "numpy.busday_offset",
  "category": "Business day operations",
  "description": "First adjusts the date to fall on a valid day according to the roll rule, then applies offsets to the given dates counted in valid days",
  "url": "https://numpy.org/doc/stable/reference/generated/numpy.busday_offset.html",
  "doc": "busday_offset(dates, offsets, roll='raise', weekmask='1111100', holidays=None, busdaycal=None, out=None)\n\nFirst adjusts the date to fall on a valid day according to the \`\`roll\`\` rule, then applies offsets to the given dates counted in valid days.\n\nParameters\n----------\ndates : array_like of datetime64[D]\n    The array of dates to process.\noffsets : array_like of int\n    The array of offsets, which is broadcast with \`\`dates\`\`.\nroll : {'raise', 'nat', 'forward', 'following', 'backward', 'preceding', 'modifiedfollowing', 'modifiedpreceding'}, optional\n    How to treat dates that do not fall on a valid day. The default is 'raise'.\n\n    * 'raise' means to raise an exception for an invalid day.\n    * 'nat' means to return a NaT (not-a-time) for an invalid day.\n    * 'forward' and 'following' mean to take the first valid day later in time.\n    * 'backward' and 'preceding' mean to take the first valid day earlier in time.\n    * 'modifiedfollowing' means to take the first valid day later in time unless it is across a Month boundary, in which case to take the first valid day earlier in time.\n    * 'modifiedpreceding' means to take the first valid day earlier in time unless it is across a Month boundary, in which case to take the first valid day later in time.\nweekmask : str or array_like of bool, optional\n    A seven-element array indicating which of Monday through Sunday are valid days. May be specified as a length-seven list or array, like [1,1,1,1,1,0,0]; a length-seven string, like '1111100'; or a string like \"Mon Tue Wed Thu Fri\", made up of 3-character abbreviations for weekdays, optionally separated by white space. Valid abbreviations are: Mon Tue Wed Thu Fri Sat Sun\nholidays : array_like of datetime64[D], optional\n    An array of dates to consider as invalid dates. They may be specified in any order, and NaT (not-a-time) dates are ignored. This list is saved in a normalized form that is suited for fast calculations of valid days.\nbusdaycal : busdaycalendar, optional\n    A \`busdaycalendar\` object which specifies the valid days. If this parameter is provided, neither weekmask nor holidays may be provided.\nout : array of datetime64[D], optional\n    If provided, this array is filled with the result.\n\nReturns\n-------\nout : array of datetime64[D]\n    An array with a shape from broadcasting \`\`dates\`\` and \`\`offsets\`\` together, containing the dates with offsets applied.",
  "code": "# C implementation for performance\n# First adjusts the date to fall on a valid day according to the roll rule, then applies offsets to the given dates counted in valid days\n#\n# This function is implemented in C as part of NumPy's core multiarray module.\n# The C implementation provides:\n# - Optimized memory access patterns\n# - Efficient array manipulation\n# - Low-level control over data layout\n# - Integration with NumPy's array object internals\n#\n# Source: C implementation in numpy/_core/src/multiarray/datetime_busday.c"
}
-/

-- TODO: Implement busday_offset
