/-!
{
  "name": "numpy.digitize",
  "category": "Histograms",
  "description": "Return the indices of the bins to which each value in input array belongs",
  "url": "https://numpy.org/doc/stable/reference/generated/numpy.digitize.html",
  "doc": "numpy.digitize(x, bins, right=False)\n\nReturn the indices of the bins to which each value in input array belongs.\n\nIf values in x are beyond the bounds of bins, 0 or len(bins) is returned as appropriate.\n\nParameters\n----------\nx : array_like\n    Input array to be binned. Prior to NumPy 1.10.0, this array had to be 1-dimensional, but can now have any shape.\nbins : array_like\n    Array of bins. It has to be 1-dimensional and monotonic.\nright : bool, optional\n    Indicating whether the intervals include the right or the left bin edge. Default behavior is (right==False) indicating that the interval does not include the right edge.\n\nReturns\n-------\nindices : ndarray of ints\n    Output array of indices, of same shape as x.\n\nRaises\n------\nValueError\n    If bins is not monotonic.\nTypeError\n    If the type of the input is complex.\n\nNotes\n-----\nIf values in x are such that they fall outside the bin range, attempting to index bins with the indices that digitize returns will result in an IndexError.\n\nThe behavior of numpy.digitize is:\n\n    indices = digitize(x, bins)\n    for i in range(x.size):\n        if x[i] < bins[0]:\n            indices[i] = 0\n        elif x[i] >= bins[-1]:\n            indices[i] = len(bins)\n        else:\n            j = 1\n            while j < len(bins):\n                if x[i] < bins[j]:\n                    indices[i] = j\n                    break\n                j += 1",
  "code": "# C implementation for performance\n# Return the indices of the bins to which each value in input array belongs\n#\n# This function is implemented in C as part of NumPy's core multiarray module.\n# The C implementation provides:\n# - Optimized memory access patterns\n# - Efficient array manipulation\n# - Low-level control over data layout\n# - Integration with NumPy's array object internals\n#\n# Source: # C implementation in numpy/_core/src/multiarray/compiled_base.c\n# Python wrapper:\n@array_function_dispatch(_digitize_dispatcher)\ndef digitize(x, bins, right=False):\n    \"\"\"\n    Return the indices of the bins to which each value in input array belongs.\n    \"\"\"\n    x = _nx.asarray(x)\n    bins = _nx.asarray(bins)\n    \n    # Check for complex dtypes\n    if x.dtype.kind == 'c':\n        raise TypeError(\"x may not be complex\")\n    \n    mono = _monotonicity(bins)\n    if mono == 0:\n        raise ValueError(\"bins must be monotonically increasing or decreasing\")\n    \n    # Check for NaN in bins, as this would break the algorithm\n    if _nx.isnan(bins).any():\n        raise ValueError(\"bins may not contain NaN\")\n    \n    if mono == -1:\n        # Reverse bins and invert result\n        return len(bins) - _nx._core.multiarray._digitize(x, bins[::-1], not right)\n    else:\n        return _nx._core.multiarray._digitize(x, bins, right)"
}
-/

-- TODO: Implement digitize
