name: Toolchain Bootstrap

on:
  push:
    branches: [ main, dev-* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: extractions/setup-just@v1
      
    - name: Set shell RC file based on OS
      id: set-rc
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          echo "rc_file=$HOME/.bashrc" >> $GITHUB_OUTPUT
        else
          echo "rc_file=$HOME/.zshrc" >> $GITHUB_OUTPUT
        fi
    
    - name: Bootstrap toolchain
      run: just bootstrap ${{ steps.set-rc.outputs.rc_file }}
      
    - name: Setup environment paths
      run: |
        # Source the environment files
        [ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
        [ -f "$HOME/.elan/env" ] && source "$HOME/.elan/env"
        
        # Add paths to GITHUB_PATH
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Verify installation
      run: |
        echo "=== Tool Versions ==="
        cargo --version || echo "cargo not found"
        elan --version || echo "elan not found" 
        uv --version || echo "uv not found"