name: Toolchain Bootstrap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install just
      uses: extractions/setup-just@v1
      
    - name: Set shell RC file based on OS
      id: set-rc
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          echo "rc_file=$HOME/.bashrc" >> $GITHUB_OUTPUT
        else
          echo "rc_file=$HOME/.zshrc" >> $GITHUB_OUTPUT
        fi
    
    - name: Bootstrap toolchain
      run: |
        just bootstrap ${{ steps.set-rc.outputs.rc_file }}
    
    - name: Setup environment paths
      run: |
        # Add paths to GITHUB_PATH for subsequent steps
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # Also export for current step
        echo "PATH=$HOME/.elan/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH" >> $GITHUB_ENV
    
    - name: Source environment files and verify installation
      run: |
        # Source environment files if they exist
        [ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
        [ -f "$HOME/.elan/env" ] && source "$HOME/.elan/env"
        
        # Export PATH for this step
        export PATH="$HOME/.elan/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
        
        # Debug: Show PATH
        echo "Current PATH: $PATH"
        
        # Debug: Check if binaries exist
        echo "Checking for binaries:"
        ls -la "$HOME/.cargo/bin/" || echo "Cargo bin directory not found"
        ls -la "$HOME/.elan/bin/" || echo "Elan bin directory not found"
        ls -la "$HOME/.local/bin/" || echo "Local bin directory not found"
        
        # Verify installations
        echo "Verifying cargo..."
        command -v cargo && cargo --version || echo "cargo not found"
        
        echo "Verifying elan..."
        command -v elan && elan --version || echo "elan not found"
        
        echo "Verifying uv..."
        command -v uv && uv --version || echo "uv not found"
