name: Toolchain Bootstrap

on:
  push:
    branches: [ main, dev-* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    
    env:
      GITHUB_ACTIONS: true
      NON_INTERACTIVE: true
    
    steps:
    - uses: actions/checkout@v4
    
    # Use unified installation script
    - name: Setup NumpySpec environment
      run: .github/scripts/setup.sh
    
    # Cache Lean dependencies (same as ci.yml)
    - name: Cache Lean dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.elan
          ~/.cache/lean
          .lake
        key: ${{ runner.os }}-lean-${{ hashFiles('lean-toolchain', 'lake-manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-lean-
    
    # Simple verification - no need for extensive checks
    - name: Verify core tools
      run: |
        echo "=== Core Tools ==="
        uv --version || echo "uv not found"
        lean --version || echo "lean not found"
        lake --version || echo "lake not found"